### ISSUE TITLE
dropExperience is not documented in wiki

### ISSUE THREAD

**Issue by Goldenlion5648** [AlmostReliable/lootjs#17]
### Version

1.20.1-2.10.4

### Describe the bug!

I saw in the code (and changelog) that the dropExperience action exists, but it was not listed in the wiki. It seems to work just fine from my testing

### Additional Context

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by LLytho** [comment]
Added. Thank you.
