### ISSUE TITLE
wrong info in  wiki  pool(callback)

### ISSUE THREAD

**Issue by Strange05** [AlmostReliable/lootjs#18]
### Minecraft Version

1.20.1

### Mod Version

1.20.1-2.11.0

### Describe the bug!

In the pool(callback) example, has:

> Example: [1, 3] is the number provider with 3 min and 10 max rolls. LootJS will randomly select a value between min and max.

but in addWeightedLoot(NumberProvider, [...items]) or addWeightedLoot([...items])
has:

> Example: [3, 10] is the number provider with 3 min and 10 max rolls. LootJS will randomly select a value between min and max.

In the last the numbers match but the pool one doesn't make much sense.

### Additions and Modifications

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by LLytho** [comment]
Updated. Thank u
