### ISSUE TITLE
Chest loot

### ISSUE THREAD

**Issue by DancinWhale** [AlmostReliable/lootjs#21]
### Describe the feature/addition!

Hi, Can you tell me how I can change the loot in chests depending on the structure (or its rarity)?

### Why would like to see this feature/addition?

-

**Comment by rlnt** [comment]
This is an issue tracker, not a support forum. Please join the Discord to ask for support after you read the wiki.
For 1.19 and 1.20: https://github.com/AlmostReliable/lootjs/wiki/1.19.2-Event
For 1.21 and above: https://docs.almostreliable.com/lootjs/

<blockquote><img src="https://opengraph.githubassets.com/b63767547d536c1b697b7ecf70be80e9a8bc6f4a8e41f1295bf78b1a7b06955d/AlmostReliable/lootjs" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/AlmostReliable/lootjs/wiki/1.19.2-Event">1.19.2 Event</a></strong></div><div>A Minecraft mod for packdevs to easily modify the loot system with KubeJS. - AlmostReliable/lootjs</div></blockquote>
<blockquote><div><strong><a href="https://docs.almostreliable.com/lootjs/">Getting Started | LootJS Wiki</a></strong></div><div>Documentation for LootJS</div></blockquote>
