### ISSUE TITLE
Unable to modify loot from BetterNether or BetterEnd

### ISSUE THREAD

**Issue by ultimatejacob27** [AlmostReliable/lootjs#22]
### Minecraft Version

1.20.1

### Mod Version

2.12.0

I am trying to modify the loot tables of blocks from Better Nether and Better End, but for some reason it does not work with those mods. There's a good chance the problem is on their side, but development seems slow over there so I was hoping to see if there's a workaround. This does not work, but I think should:
`LootJS.modifiers((event) => {
    event.addBlockLootModifier("betterend:thallasium_ore").addLoot("minecraft:flint");
});`

Feel free to close the issue if there's nothing that can be done on this side of things.

### Additions and Modifications

Yes

### Additions and Modifications Description

Here's the modpack in question, although I think the only relevant mods are KubeJS, LootJS, BetterNether, BetterEnd, and BCLib.
https://www.curseforge.com/minecraft/modpacks/minecraft-ultimate-rpg-edition

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
It is an issue on their end. They hardcode the drop. There is no loot table for the ore.
![image](https://github.com/user-attachments/assets/0f9e9278-6e1f-464d-959c-cef12ede6e95)
