### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by Wudji** [AlmostReliable/lootjs#4]
### Version

1.16.5-1.0.0

### Describe the bug!

thenAddWeighted in https://github.com/AlmostReliable/lootjs-forge/wiki/1.16.5-Actions#thenadditems doesn't work
![image](https://user-images.githubusercontent.com/93850120/164968935-1c72c679-468e-41a2-be51-a7860deab094.png)

### Crash Report

-

### Log

-

### Additional Context

Yes

### Modifications

![image](https://user-images.githubusercontent.com/93850120/164968946-66322942-4361-43ba-bd39-8c2a950b6ba9.png)

### Did the issue happen in singleplayer or on a server?

Both

**Comment by LLytho** [comment]
Hey,

adding weighted loot only works for 1.18+, sorry.

**Comment by rlnt** [comment]
The wiki mentions the version the respective function supports in the side panel. Sorry for the inconvenience but 1.16 reached EOL.

**Comment by Wudji** [comment]
> The wiki mentions the version the respective function supports in the side panel. Sorry for the inconvenience but 1.16 reached EOL.

![img](https://user-images.githubusercontent.com/93850120/165507948-cdaece7a-1b55-4b64-896a-58f7e3206ac7.png)

**Comment by LLytho** [comment]
Github wikis ... fixed it. Sorry for that.
