### ISSUE TITLE
incompatibility with CraftTweaker

### ISSUE THREAD

**Issue by arrisar** [AlmostReliable/lootjs#7]
### Version

lootjs-fabric-1.18.2-2.7.4

### Describe the bug!

All in the title really. After a couple hours of one-by-one adding mods to my pack to validate where the issue lies, eventually isolated it to this mod.

In short, there are no mob or entity drops while LootJS is installed. I tried enabling logging and there is no output.

### Additional Context

Yes

### Modifications

The pack is Be Yourself 0.2.1, found here: https://www.curseforge.com/minecraft/modpacks/be-yourself

### Did the issue happen in singleplayer or on a server?

Both

**Comment by LLytho** [comment]
Look like CraftTweaker and LootJS together fails. I will look into it

**Comment by arrisar** [comment]
Appreciate it! Sorry don't have the time atm to help out on the code dive, but let me know if there's anything else I can test/help with. Have only disabled the mod on the server, keen to keep it in the pack.

**Comment by LLytho** [comment]
All good! Thanks for reporting. The problem currently is that CT and LootJS mixin into the `LootTable` class. I need to come up with a good solution. Maybe I also need to talk to Silk, who made the CT mixin for loot tables, if I don't find a good solution to fit the problem.

Ofc LootJS should not break looting when CT is installed, but on the other side I see no point of having CT and Kube installed together. They both do the same.
