### ISSUE TITLE
Scripts fail to apply on existing worlds with KubeJS Fabric 1902.6.0-build.119

### ISSUE THREAD

**Issue by SplendidAlakey** [AlmostReliable/lootjs#9]
### Version

2.7.5

### Describe the bug!

1. Install [KubeJS Fabric 1902.6.0-build.119](https://www.curseforge.com/minecraft/mc-mods/kubejs/files/4085692)
2. Install LootJS 2.7.5
3. Create a very simple script, using LootJS
4. Launch the game, create a new world - no errors appear
5. Exit the world and re-enter it - now LootJS scripts fail to load

The script I'm using to test this is very simple:

```
LootJS.modifiers((event) => {
	event
		.addEntityLootModifier("minecraft:bee")
		.removeLoot("mcdw:item_bee_stinger");
});
```

Rolling back to [KubeJS Fabric 1902.6.0-build.117](https://www.curseforge.com/minecraft/mc-mods/kubejs/files/4082491) solves the issue.

### Log

https://gist.github.com/SplendidAlakey/e3d9c2f4f298a1d1c0ed9aaeaa06a186

### Additional Context

Yes

### Modifications

I'm using LootJS to remove loot from [MC Dungeons Weapons](https://www.curseforge.com/minecraft/mc-mods/mcdw/files/3971563), but I don't think it matters, judging by the logs.

### Did the issue happen in singleplayer or on a server?

Both

**Comment by LLytho** [comment]
New kubejs version... I have no words for this... 

Thank you for the report! Will fix this later.

**Comment by SplendidAlakey** [comment]
Also, completely unrelated to this issue, but you seem to not have KubeJS set as a hard dependency in [fabric.mod.json](https://github.com/AlmostReliable/lootjs/blob/1.18/fabric/src/main/resources/fabric.mod.json). Not critical at all, but probably worth adding that, so that a crash, caused by not having KubeJS, would be descriptive in telling people to install KubeJS, rather than throw some messy crash log.

**Comment by LLytho** [comment]
> Also, completely unrelated to this issue, but you seem to not have KubeJS set as a hard dependency in [fabric.mod.json](https://github.com/AlmostReliable/lootjs/blob/1.18/fabric/src/main/resources/fabric.mod.json). Not critical at all, but probably worth adding that, so that a crash, caused by not having KubeJS, would be descriptive in telling people to install KubeJS, rather than throw some messy crash log.

Yep, added this too now. Thanks

**Comment by LLytho** [comment]
New version 2.7.6 uploaded to CF. Waiting for approval! Should hopefully just take a few minutes.
